image: gcc

stages:
  - build

building:
  stage: build
  
  before_script:
    - apt update 
    - apt -y install make cmake libgtest-dev

  script: 
    - mkdir -p build 
    - cd build
	- cmake ..
    - make
